### ISSUE TITLE
Using the CLI tool, settings from the UI

### ISSUE THREAD

**Issue by fullofcaffeine** [teejee2008/aptik-plus#10]
My backups system consists of shell scripts that trigger borg and then rsync them to the cloud (wasabi). I'd like to trigger the aptik backup and then rsync its repo to the cloud. 

It seems simple enough to accomplish taht, but I have a question: does the CLI tool respect the settings (selected items to backup, excludes, etc) from the gtk ui interface?

**Comment by teejee2008** [comment]
Yes. The CLI tool will respect selections made in GUI tool. Selections made in GUI tool are saved to a file named _selections.list_ in backup folder. This file is read by the CLI tool when it runs.

**Comment by fullofcaffeine** [comment]
Thanks!
