### ISSUE TITLE
Where is the backup? It never asks me. 

### ISSUE THREAD

**Issue by bobnolte** [teejee2008/aptik-plus#11]
Just bought Aptik today. Fresh Linux Mint 18.3 load a few days ago. See attached log.
uninstalled and reinstalled.
Thanks in advance.

[2020-02-10-Lenovo Backup.tar.gz](https://github.com/teejee2008/aptik-plus/files/4183884/2020-02-10-Lenovo.Backup.tar.gz)

**Comment by teejee2008** [comment]
Looking at the log it seems you have saved the backups to `/root`

Click the **Select** button to select the Backup Path.

![image](https://user-images.githubusercontent.com/12488854/74207852-2c050f80-4ca7-11ea-92ca-a8c90c58b3be.png)

**Comment by bobnolte** [comment]
I was in error. Since the Backup Path was at the top, I presumed that it
meant the path that I am backing up. Maybe it should say, "Path to Backup.
Thanks for your quick response.
Bob Nolte.

**Comment by bobnolte** [comment]
"Path to *the* Backup"
