### ISSUE TITLE
E: Prune: Failed to open Borg repository

### ISSUE THREAD

**Issue by tyler820201** [teejee2008/aptik-plus#12]
I have the latest Aptik 20.02.1 and Borg 1.1.5 version.
When my backup has completed i have got error message Failed to open Borg repository Incorrect password? I was trying to update Borg to 1.1.10 but the latest is 1.1.5 wich will be installed. Also was trying to reinstall Aptik.
Will my  created backup usable or not? If not what need to do??
 I am using Kubuntu 18.04 LTS 
![Screenshot_20200313_120050](https://user-images.githubusercontent.com/51120214/76621093-e732f980-652e-11ea-886b-2f60e58c9c5e.png)

**Comment by teejee2008** [comment]
From the screenshot it looks like the backup completed successfully. It then tried to prune the backups (to remove older data) and failed because the password was incorrect.

Select the "Restore" option in the Main window and click the "Home data" button.

![image](https://user-images.githubusercontent.com/12488854/76640866-ae1e7780-6576-11ea-8db4-4d735f5387f1.png)

Check the "Original size" column. If it shows a non-zero size then the backups are good and the password is correct.

![image](https://user-images.githubusercontent.com/12488854/76640775-8b8c5e80-6576-11ea-8b04-7e63f3828fc3.png)

**Comment by tyler820201** [comment]
![Screenshot_20200313_175047](https://user-images.githubusercontent.com/51120214/76642385-66d2bf80-6553-11ea-89f3-3e3aa56a4737.png)
It looks like password is incorrect. However i did not set up any password before doing backup (leaving blank)

**Comment by teejee2008** [comment]
Try to enter password as 'aptik' and see if that works

**Comment by tyler820201** [comment]
Yes, that was the default settings. It was working until the last backup made today. The previous backup has been completed without this issue on November last year. Today is the first time having this problem. The default passw. was "aptik"

**Comment by teejee2008** [comment]
Does it work with password as 'aptik' ?

**Comment by tyler820201** [comment]
No it was not working this morning. I am trying now making a new backup clear home folder for passwords and re-setting "aptik" again for password. It takes time as my home folder is huge...

**Comment by tyler820201** [comment]
No it was not working with "aptik". I have got the same error
![Screenshot_20200313_181240](https://user-images.githubusercontent.com/51120214/76643929-53752380-6556-11ea-87a0-be0d9b8e1231.png)

**Comment by teejee2008** [comment]
Ok... Select "Restore", enter password as 'aptik' in Settings window, and click the "Home Data" button. Tell me if it works or if it still shows the incorrect password message.

When a new password is entered in Settings window, Aptik will behave differently depending on whether the mode is selected as "Backup" or "Restore".

When mode is "Backup", entering a new password in Settings window will change the password for existing backups. It will be used when taking the next backup.

When mode is "Restore", entering a new password in Settings window will only use it to decrypt the existing backups. It will be checked when you click the "Home Data" button.

**Comment by tyler820201** [comment]
![Screenshot_20200313_184441](https://user-images.githubusercontent.com/51120214/76646203-ddbf8680-655a-11ea-9270-17ba5afeab7d.png)
Unfortunatelly no luck
I did click restore and giving enter "aptik" for new password.

**Comment by tyler820201** [comment]
Now i did a fully new backup before starting i was double check passw. "aptik" is correct but i have the same issue.
![Screenshot_20200313_185923](https://user-images.githubusercontent.com/51120214/76647267-c7b2c580-655c-11ea-8fd6-a780b8e875f0.png)

**Comment by tyler820201** [comment]
This is the first time using 20.02.1 version of Aptik. With the previous version i have not got issue. 19.10.2

**Comment by teejee2008** [comment]
Your backup is getting created successfully. 

You can ignore the prune error.  It will be fixed in the next update.

**Comment by tyler820201** [comment]
Great.
Thanks

**Comment by tyler820201** [comment]
I just want confirm that version 20.03 working fine with no issues.
Thanks

**Comment by teejee2008** [comment]
Thanks for the confirmation
