### ISSUE TITLE
E: Unable to fetch some packages; try '-o APT::Get::Fix-Missing=true' to continue with missing packages

### ISSUE THREAD

**Issue by ccase01** [teejee2008/aptik-plus#14]
?  Not sure how to proceed with this one....

**Comment by teejee2008** [comment]
Please provide the full log

**Comment by ccase01** [comment]
Actually nm again.... this was apparently just for Spotify?  No need anyway.  Great product btw. Happy to pay for it.  Just need to remember to think things through before posting now... ;)
