### ISSUE TITLE
Required: 20.06 Found Unknown 

### ISSUE THREAD

**Issue by mightywomble** [teejee2008/aptik-plus#15]
I have two users on my laptop one is local one is AD. Both have sudo access.

I successful took a backup of the local user rebooted and logged in as the AD user and get

Please install the latest version of Aptik
Required 20.06
Found Unknown

I'm guessing the first run creates a reference file?

**Comment by teejee2008** [comment]
Aptik does not support AD and network accounts. You need to be logged-in as a local user.

**Comment by mightywomble** [comment]
Bugger, was that documented anywhere? Did I miss that? 😀

**Comment by teejee2008** [comment]
Yes. See the last point in system requirements section:
https://teejeetech.in/buy-aptik/

**Comment by mightywomble** [comment]
Ok, my bad, no worries.. nice software by the way..
