### ISSUE TITLE
Can't authenticate 2'nd system

### ISSUE THREAD

**Issue by RayLaBrecque** [teejee2008/aptik-plus#16]
I am using Aptik to migrate to a new Linux system.  I installed, authenticated and used Aptik on the source system but when attempting to authenticate on the 2'nd system it will not take my license.

Do I need to purchase a license for each systerm?

**Comment by teejee2008** [comment]
Make sure you are entering the key correctly. Please send me an email if it still doesn't work.

**Comment by RayLaBrecque** [comment]
Apologize for the delayed response-I know you marked this ticket as closed in another email. but I am afraid it still does not work.  I have very carefully performed a copy and paste to enter the authentication key on the 2'nd machine but it continually fails.This is the key I a, entering:8o8ry8rJTpR1kvWMs89PSsgrSpJ1z6/MT8qMi4dwbZPi8gtTM9OyM7SzkworPZ2M7bWC9Ix0tew8DN20wj0DTbQMfQLsAAAAAP8=The error message recieved is:"Your authentication attempt was unsuccessful. Please try again."Is there a log file I can look at to see more details?Thanks,Ray L.-----Original Message-----
