### ISSUE TITLE
How to restore to a new system

### ISSUE THREAD

**Issue by tespro** [teejee2008/aptik-plus#2]
Running Ubuntu 18.04, I backed-up  3 APT packages and one Deb pkg  onto a 16gig USB. (Only used one gig which surprised me.) Put the USB in a new system which has Ubuntu 18.04. On the USB there's an APTIK icon but nothing happened when I clicked on it. There's also a short shell script, restore-all.sh which wouldn't execute in terminal.  I'm stumped. How do I restore without having APTIK on the new system?

**Comment by tespro** [comment]
P.S. I'm using the paid version.

**Comment by tespro** [comment]
Thanks for your reply.

Lacking internet on the new computer, there's no easy way to install APTIK,
right?

**Comment by teejee2008** [comment]
Internet connection is required for restoring packages, repos, etc. Installing Aptik without having an internet connection won't be of much use.
