### ISSUE TITLE
Nothing displayed for flatpak/deb/packages installed on Pop_OS! 20.10

### ISSUE THREAD

**Issue by AurelienKun** [teejee2008/aptik-plus#20]
Nothing is displayed on the GUI but when I start the backup all process, it seems to backup everything but flatpak apps...

 
![Screenshot from 2021-03-28 23-30-40](https://user-images.githubusercontent.com/3368866/112768753-dd871180-901d-11eb-8738-4653dede4744.png)
![Screenshot from 2021-03-28 23-31-02](https://user-images.githubusercontent.com/3368866/112768754-dd871180-901d-11eb-8782-1699e8c586c5.png)
![Screenshot from 2021-03-28 23-31-32](https://user-images.githubusercontent.com/3368866/112768755-de1fa800-901d-11eb-997d-b64674eccb79.png)

**Comment by AurelienKun** [comment]
I can send you the logs in private if needed.

**Comment by teejee2008** [comment]
Please send the log file to support@teejeetech.com

**Comment by AurelienKun** [comment]
Thank you ! The problem has been fixed in 21.02.4 
Excellent 👍🏻
