### ISSUE TITLE
Can't install with the code

### ISSUE THREAD

**Issue by jkcs2021** [teejee2008/aptik-plus#21]
I tried to install the aptik application in my Ubuntu 20.04.2 LTS with the code in the email (wget -O - https://www.teejeetech.com/install-aptik.sh | bash...) but it failed and the following error messages were shown:

> Installing 'apt-transport-https'... 
Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:2 http://ppa.launchpad.net/teejee2008/ppa/ubuntu focal InRelease         
Hit:3 http://us.archive.ubuntu.com/ubuntu focal InRelease                      
Ign:4 http://ppa.launchpad.net/webupd8team/java/ubuntu focal InRelease   
Get:5 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Err:6 http://ppa.launchpad.net/webupd8team/java/ubuntu focal Release           
  404  Not Found [IP: 91.189.95.85 80]
Get:7 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]   
Reading package lists... Done     
E: The repository 'http://ppa.launchpad.net/webupd8team/java/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Please kindly check and advise how I could get it installed.

Thanks!

**Comment by teejee2008** [comment]
`E: The repository 'http://ppa.launchpad.net/webupd8team/java/ubuntu focal Release' does not have a Release file.`

Remove the webupd8team ppa. It is broken.
