### ISSUE TITLE
Start error on Ubuntu Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by tomasz-rejman-zen-com** [teejee2008/aptik-plus#22]
Fresh install on Ubuntu 20.04.2 LTS, by provided installation link from email:

**Removed**

looks like everything was installed properly but after I try to run it it will show me the error:

"Please install the latest version of Aptik
Required: 21.02.6"

![Screenshot from 2021-05-04 18-53-35](https://user-images.githubusercontent.com/52916820/117040458-34ad8f80-ad0a-11eb-8d9d-b952da20e254.png)

And more info: If I try to run it from a command it shows:
Segmentation fault

**Comment by teejee2008** [comment]
This is a public tracker. Please don't post installation links here.

**Comment by teejee2008** [comment]
Send me the output of installation command.

From the message it seems like the aptik package is not installed.

Run the following and let me know the output.

sudo apt install aptik

**Comment by tomasz-rejman-zen-com** [comment]
If I try to run it from a command it shows:
Segmentation fault

**Comment by tomasz-rejman-zen-com** [comment]
sudo wget -O - https://www.teejeetech.com/install-aptik.sh | bash -s -- "Oj2oeAwt5J"
--2021-05-04 18:43:24--  https://www.teejeetech.com/install-aptik.sh
Resolving www.teejeetech.com (www.teejeetech.com)... 162.241.148.10
Connecting to www.teejeetech.com (www.teejeetech.com)|162.241.148.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4189 (4,1K) [application/x-sh]
Saving to: ‘STDOUT’

-                                         100%[====================================================================================>]   4,09K  --.-KB/s    in 0s      

2021-05-04 18:43:26 (52,6 MB/s) - written to stdout [4189/4189]


Linux Family: debian


> Pre-install dependencies... 
OK

> Importing public key... 
Created: /usr/share/keyrings/teejeetech-aptik-keyring.gpg

> Adding repository... 
deb [signed-by=/usr/share/keyrings/teejeetech-aptik-keyring.gpg] https://packages.teejeetech.com/aptik/Oj2oeAwt5J stable main
Created: /etc/apt/sources.list.d/teejeetech-aptik.list

> Refreshing package information... 
Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:2 http://pl.archive.ubuntu.com/ubuntu focal InRelease                                                                                                
Hit:3 http://pl.archive.ubuntu.com/ubuntu focal-updates InRelease                                                                                        
Hit:4 http://pl.archive.ubuntu.com/ubuntu focal-backports InRelease                                              
Hit:5 https://packages.microsoft.com/repos/ms-teams stable InRelease                                           
Hit:6 https://packages.teejeetech.com/aptik/Oj2oeAwt5J stable InRelease                                        
Reading package lists... Done

> Installing packages... 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libavahi-core7 libdaemon0 libgstreamer-plugins-bad1.0-0 libva-wayland2
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 3 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/1 785 kB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 235140 files and directories currently installed.)
Preparing to unpack .../aptik_21.02.6_amd64.deb ...
Unpacking aptik (21.02.6) over (21.02.6) ...
Preparing to unpack .../aptik-assets_21.02.6_amd64.deb ...
Unpacking aptik-assets (21.02.6) over (21.02.6) ...
Preparing to unpack .../aptik-gtk_21.02.6_amd64.deb ...
Unpacking aptik-gtk (21.02.6) over (21.02.6) ...
Setting up aptik (21.02.6) ...
Setting up aptik-assets (21.02.6) ...
Setting up aptik-gtk (21.02.6) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...

> Installed successfully 

Start Aptik from the Applications menu on your desktop,
or type 'aptik-gtk-launcher' in a command window.

Type 'aptik' in a command window to use the command-line version

**Comment by teejee2008** [comment]
Please send me the output by email. You are repeatedly posting the installation commands here.

support@teejeetech.com
