### ISSUE TITLE
Warn users when device isn't present

### ISSUE THREAD

**Issue by GammaGames** [teejee2008/aptik-plus#23]
I had set up my computer to back up at `/media/[username]/Backup/YYYY-MM-DD`, and when you select a folder it shows the text:
![image](https://user-images.githubusercontent.com/7832163/132387816-d0a32ef5-d09e-4fd5-9fb2-e219ea69832f.png)

However, if the device is plugged in and not mounted it just says "NA":
![image](https://user-images.githubusercontent.com/7832163/132387890-1f13da0a-d9c3-4c5d-b7c5-33241b23b7e8.png)

It would be very nice if it had some warning text telling the user that they are about to write to the local hard drive. I don't use the program often, and the issue caused me lose all my backups from the past year when I went to reinstall my os and everything was "backed up" locally :/

**Comment by teejee2008** [comment]
Added in [v21.12](https://teejeetech.com/2021/12/05/aptik-21-12/)
