### ISSUE TITLE
Need to install borgbackup?

### ISSUE THREAD

**Issue by GammaGames** [teejee2008/aptik-plus#4]
I ran into a hiccup trying to restore on elementary OS, where borg wasn’t installed so I couldn’t run the restore script. Is this expected?

**Comment by teejee2008** [comment]
The restore script can be used only if dependencies are installed. You need to install the app before running the restore script.

**Comment by GammaGames** [comment]
Why not install the ppa and aptik+dependencies with the `restore-all.sh` script then, either by default or with a flag? You already have a script to add the PPA and install the program, why not just fetch and run that at the start?

**Comment by teejee2008** [comment]
That is not the purpose of this script. Installation must be done before running it.
