### ISSUE TITLE
Restore without password

### ISSUE THREAD

**Issue by GammaGames** [teejee2008/aptik-plus#5]
I didn't want a password, so I removed it and left the text input blank when I made my backup.

Now that I'm trying to restore my home directory and system files, I'm getting an error that I have the wrong password.

![image](https://user-images.githubusercontent.com/7832163/68415852-85155280-0150-11ea-9fcd-f073e8eccfda.png)

**Comment by teejee2008** [comment]
If you leave the field blank it will use 'aptik' as the default password. Leave the field blank or type in 'aptik' when doing the restore.

**Comment by GammaGames** [comment]
I can't seem to get it to work, is there any way to test a password with borg on the command line?

![Screen record from 2019-11-12 07 59 40](https://user-images.githubusercontent.com/7832163/68682473-6b925300-0522-11ea-9e2f-dbe82d8ac3c9.gif)

Why not make the password input required as well, to prevent possible confusion in the future?

**Comment by teejee2008** [comment]
Try the following comand:
BORG_PASSPHRASE='aptik' borg list backup-path/home/files/

If password is correct it will list snapshots

**Comment by GammaGames** [comment]
That does not work. However, using `BORG_PASSPHRASE=''` does work. I was able to extract the files with the command `BORG_PASSPHRASE='' borg extract backup-path/home/files/::snapshot`

**Comment by teejee2008** [comment]
This is fixed in v20.01. Leave the password blank if you don't want to use encryption.
