### ISSUE TITLE
GUI doesn't start when using xmonad

### ISSUE THREAD

**Issue by fullofcaffeine** [teejee2008/aptik-plus#8]
Hi!

I just bought Aptik and while trying to start it from xmonad, the GUI isn't shown. The CLI seems to work great though.

I'm using a vanilla xmonad without an additional desktop env on Mint 18.03. If I boot into Cinnamon, it works great.

Any hints on how I can fix my system so that the GUI starts from my xmonad setup?

If you need additional info about the system, let me know.

Thanks in advance!

**Comment by teejee2008** [comment]
Will check and let you know. 

Does Xmonad login to a Wayland session? The desktop session must support GUI applications that run with Admin priviledges.

**Comment by fullofcaffeine** [comment]
Hmm, actually `aptik-gtk-launcher` works great. I was actually trying to run `aptik` which is the CLI tool. Sorry for the noise.
