### ISSUE TITLE
Deselected items

### ISSUE THREAD

**Issue by fullofcaffeine** [teejee2008/aptik-plus#9]
Hi!

I noticed that when clicking in a backup category (say, "APT Packages"), there are several items that are deselected in the default configuration. Why? What is the criteria used to __not__ select these items to be part of the backup? Should I select them?

Example:

![last2](https://user-images.githubusercontent.com/81248/72703502-61409680-3b1b-11ea-9255-c6988743c1e5.png)

Thanks.

**Comment by fullofcaffeine** [comment]
Ping...

**Comment by teejee2008** [comment]
This is mentioned in the User Manual on page 18. You can open the Manual using the Help button in GUI or by opening /usr/share/aptik/MANUAL.pdf

2. List of installed packages are filtered to *deselect* the following:

   *  Kernel packages - `linux-headers*`, `linux-signed*`, `linux-tools*`, `linux-image*`
   *  Library packages - `lib*` - These are usually dependencies for other software and will be installed automatically if needed.
   *  Non-native (foreign) packages. For example,  `i386` packages on an `amd64` system. These are usually dependency packages and will be auto-installed if needed.

These defaults are meant to work for all users and cause the least problems on restore. There is no need to select an unselected package unless there is some specific package that you wish to keep that is getting excluded by the defaults.

**Comment by fullofcaffeine** [comment]
Thanks!
